### ISSUE TITLE
Cannot plot an audio container

### ISSUE THREAD

**Issue by lesept777** [DCASE-REPO/dcase_util#43] opened 2024-01-17 14:44 UTC
#### Description
Cannot plot an audio container

#### Steps/Code to Reproduce
audio_container = dcase_util.containers.AudioContainer().load( filename=dcase_util.utils.Example.audio_filename())
audio_container.plot()

#### Actual Results
Traceback (most recent call last):

  Cell In[38], line 1
    audio_container.plot()

  File ~\AppData\Local\anaconda3\Lib\site-packages\dcase_util\containers\audio.py:1808 in plot
    self.plot_wave(**kwargs)

  File ~\AppData\Local\anaconda3\Lib\site-packages\dcase_util\containers\audio.py:1925 in plot_wave
    from librosa.display import waveplot

ImportError: cannot import name 'waveplot' from 'librosa.display'
#### Versions
Windows-10-10.0.19045-SP0
Python 3.9.6 (tags/v3.9.6:db3ff76, Jun 28 2021, 15:26:21) [MSC v.1929 64 bit (AMD64)]
NumPy 1.24.1
SciPy 1.10.1
Matplotlib 3.7.1
librosa 0.10.0.post2

**Comment by toni-heittola** [comment] 2024-03-22 12:25
This issue was fixed with commit 85d28bb and will be included in the next release. The issue was caused by breaking changes in the Librosa library (version >0.9).

**Closed as completed by toni-heittola** 2024-03-22 12:25 UTC
